version: '3'
services:
    reactapp:
        image: luisfellipe/reactapp
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/src'
            - '/src/node_modules'
        ports: 
            - 8081:8081
        environment: 
            - NODE_ENV=development
        

